### ISSUE TITLE
NoRegisteredSWRLRuleEnginesException: no registered SWRL rule engines

### ISSUE THREAD

**Issue by Buglish** [protegeproject/swrlapi#13]
Hi,

I am running a simple SWRL rule on a selected OWL ontology and as soon as the createSQWRLQueryEngine is initiated it throws an error that is not clear of what is wrong.

-Release-
<version>1.0.0-beta-11-SNAPSHOT</version>

-Source-
String SOURCE= "C:\IdeaProjects\SQWRL\java.owl";
OWLOntology ontology = ontologyManager.loadOntologyFromOntologyDocument(new File(SOURCE));
SQWRLQueryEngine queryEngine = SWRLAPIFactory.createSQWRLQueryEngine(ontology);

-Stack Trace-
org.swrlapi.exceptions.NoRegisteredSWRLRuleEnginesException: no registered SWRL rule engines
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSQWRLQueryEngine(DefaultSWRLRuleAndQueryEngineFactory.java:83)
	at org.swrlapi.factory.SWRLAPIFactory.createSQWRLQueryEngine(SWRLAPIFactory.java:90)
	at org.sjdp.sqwrl.GUI.parseTextToQueryAndRun(GUI.java:300)
	at org.sjdp.sqwrl.GUI.actionPerformed(GUI.java:223)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by martinjoconnor** [comment]
Have you included the Drools SWRLAPI engine?

https://github.com/protegeproject/swrlapi#getting-started

"If you'd like to be able to execute SWRL rules or SQWRL queries you will need a SWRLAPI-based rule engine implementation. Currently, a Drools-based SWRL rule engine implementation is provided. This implementation is also hosted on Maven Central. "

**Comment by Buglish** [comment]
Thank you for pointing me in right direction. I included all the dependencies of both swrlapi and drools.

What version of org.kie.api should I include.

If i add all the dependencies for the two API DOMs it complained that KieBaseOption is not found which is not in any of the dependencies.

Exception: java.lang.NoClassDefFoundError. Message: org/kie/api/conf/KieBaseOption

**Comment by martinjoconnor** [comment]
Have you tried using the build project to build everything on your machine:

https://github.com/protegeproject/swrltab-project

Take a look at the POM in the SWRLTab standalone project:

https://github.com/protegeproject/swrltab

If is a simple application that includes the SWRLAPI and Drools engine as dependencies.

**Comment by Buglish** [comment]
Thank you for the link. I have used the approved dependencies of swrlapi-1.0.0-beta-10 and swrlapi-drools-engine-1.0.0-beta-11 and set the scope to runtime for it.

Since the dependency error is not related to swrlapi, I will post on drools-engine issues page.

org.swrlapi.exceptions.SWRLRuleEngineException: Error creating query engine Drools. Exception: java.lang.RuntimeException. Message: Unable to load dialect 'org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration:java:org.drools.compiler.rule.builder.dialect.java.JavaDialectConfiguration'
