### ISSUE TITLE
SWRLapi with Pellet Reasoner

### ISSUE THREAD

**Issue by zouma45** [protegeproject/swrlapi#30]
Hi, 
i am working on an Ontology Based Decision support system, and  i added SWRLapi to Maven dependecies, But, once  i added the Pellet dependency, i got this Exception:

`Exception in thread "main" java.lang.AbstractMethodError
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:111)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:59)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
	at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:97)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
	at org.swrlapi.example.SWRLAPIExample.main(SWRLAPIExample.java:60)
`

 
Is Pellet not compatible with SWRLapi ? 

The maven dependency i added is the following: 

` 		<dependency>
			<groupId>com.github.ansell.pellet</groupId>
			<artifactId>pellet-owlapiv3</artifactId>
			<version>2.3.6-ansell</version>
		</dependency> `

**Comment by martinjoconnor** [comment]
From the above stack dump it seems that the code is failing before even getting to SWRLAPI-related functionality. Have you tried a basic project with just Pellet?

Note that the SWRLAPI and Pellet are completely unrelated. The SWRLAPI comes with its own OWL 2 RL-based reasoner and does not use third party OWL or SWRL reasoners. The SWRLAPI will essentially ignore any reasoners you install.

**Comment by zouma45** [comment]
I actually tried using Pellet alone, it works perfectly, it only when they are together in the same project, i get this issue.

**Comment by martinjoconnor** [comment]
The SWRLAPI uses the OWLAPI. I am wondering if the version of the OWLAPI Pellet is expecting is different. The 2.0.0 version of the SWRLAPI is using the 4.2.7 release of the OWLAPI: 

https://github.com/protegeproject/swrlapi-parent/blob/master/pom.xml

Is seems from above that Pellet is expecting the 3.x.x release of the OWLAPI.

**Comment by zouma45** [comment]
Yes, Pellet is using version 3.xx, So there is a conflict with both versions of OWLapi ?
and we can't put both dependencies together ?

**Comment by martinjoconnor** [comment]
There are significant differences between the version 3 and version 4 of the OWLAPI.

Is there a later version of Pellet that uses version 4? 

I would post this question to the Protege mailing list if not:

http://protege.stanford.edu/support.php

**Comment by zouma45** [comment]
I think it is the last version, i will post the question to the Protege mailing list.

**Comment by zouma45** [comment]
So for everyone who got this issue, here is a fix: 

       <dependency>
        <groupId>com.github.ansell.pellet</groupId>
        <artifactId>pellet-owlapiv3</artifactId>
        <version>2.3.6-ansell</version>
        <exclusions>
            <exclusion>
                <groupId>com.github.ansell.owlapi</groupId>
                <artifactId>owlapi-api</artifactId>
            </exclusion>
            <exclusion>
                    <groupId>com.github.ansell.owlapi</groupId> 
                    <artifactId>owlapi-impl</artifactId>
            </exclusion>
            <exclusion>
                    <groupId>com.github.ansell.owlapi</groupId>
                    <artifactId>owlapi-parsers</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
