### ISSUE TITLE
SWRLParseException at literal value

### ISSUE THREAD

**Issue by nmerkle** [protegeproject/swrlapi#31]
Hi,

I am using since a longer time the SWRLApi and it worked until today what is really strange. I get a SWRLParseException although I have nothing changed in my ontology and implementation. The exception is always thrown if I have the following term in the rule: HasState(?l, "ON") 
The "ON" value is in my ontology and rule a string literal and before the rule is parsed, the appropriate axioms are set in the ontology.  So I have no idea at all, what is going wrong there, especially since it worked before. Could it be that something has changed in the swrlapi implementation. I guess Maven updates my projects with the newest available version. Below you can find the rule and subsequently the exception stack trace:
Thanks in advance.

> Rule: Attribut-3AHasConfidence(Switch_Light_On_Intention, ?confidence) ^ swrlb:greaterThanOrEqual(?confidence, 0.5) ^ Kategorie-3AAction(Switch_Light_on) ^ Kategorie-3AAmbientLightSensor(?ambie) ^ Kategorie-3AAssistedPerson(?u) ^ Kategorie-3AEyeTrackingGlass(?e) ^ Kategorie-3AIntention(Switch_Light_On_Intention) ^ Kategorie-3ALamp(?l) ^ Attribut-3AHasFunctionality(?l, Switch_Light_on) ^ Attribut-3AHasState(?l, "OFF") ^ Attribut-3AHasAction(Switch_Light_On_Intention, Switch_Light_on) ^ Attribut-3AHasInFocus(?e, ?l) ^ Attribut-3AHasState(?ambie, ?ambientState) ^ swrlb:lessThan(?ambientState, 500) -> Attribut-3AHasIntention(?u, Switch_Light_On_Intention)

org.swrlapi.parser.SWRLParseException: Expecting variable or OWL individual name, got 'OFF'
      at org.swrlapi.parser.SWRLParser.parseSWRLIArgument(SWRLParser.java:322)
      at org.swrlapi.parser.SWRLParser.parseSWRLObjectPropertyAtomArguments(SWRLParser.java:226)
      at org.swrlapi.parser.SWRLParser.parseSWRLAtom(SWRLParser.java:198)
      at org.swrlapi.parser.SWRLParser.parseSWRLRule(SWRLParser.java:105)
      at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.createSWRLRule(DefaultSWRLAPIOWLOntology.java:217)
      at org.swrlapi.factory.DefaultSWRLAPIOWLOntology.createSWRLRule(DefaultSWRLAPIOWLOntology.java:211)
      at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngine.createSWRLRule(DefaultSWRLRuleAndQueryEngine.java:247)
      at org.swrlapi.example.MyRuleEngine.reason(MyRuleEngine.java:219)
      at org.swrlapi.example.SherlockSocket.onMessage(SherlockSocket.java:306)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
      at java.lang.reflect.Method.invoke(Unknown Source)
      at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
      at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:72)
      at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextMessage(JettyAnnotatedEventDriver.java:225)
      at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
      at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
      at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver.onTextFrame(JettyAnnotatedEventDriver.java:217)
      at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:160)
      at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)
      at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)
      at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
      at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)
      at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:628)
      at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:476)
      at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
      at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
      at java.lang.Thread.run(Unknown Source)

**Comment by nmerkle** [comment]
Ok, now I found the error. It was in my ontology. So no issue with the swrlapi. So I will close again the issue.
