### ISSUE TITLE
Error while adding SWRL rules to OWL file

### ISSUE THREAD

**Issue by rayaprolu143** [protegeproject/swrlapi#36]
Exception in thread "main" java.lang.AbstractMethodError
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.loadFactories(OWLAPIServiceLoaderModule.java:111)
	at org.semanticweb.owlapi.OWLAPIServiceLoaderModule.configure(OWLAPIServiceLoaderModule.java:59)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at org.semanticweb.owlapi.apibinding.OWLManager.createInjector(OWLManager.java:89)
	at org.semanticweb.owlapi.apibinding.OWLManager.instatiateOWLOntologyManager(OWLManager.java:97)
	at org.semanticweb.owlapi.apibinding.OWLManager.createOWLOntologyManager(OWLManager.java:58)
	at SWRLrules.main(SWRLrules.java:22)

The dependencies added to the pom.xml file as follows:

        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>pellet-owlapi-ignazio1977</artifactId>
            <version>2.4.0-ignazio1977</version>
        </dependency>

        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-apibinding</artifactId>
            <version>3.5.2</version>
        </dependency>

        <dependency>
            <groupId>edu.stanford.swrl</groupId>
            <artifactId>swrlapi</artifactId>
            <version>2.0.4</version>
        </dependency>

        <dependency>
            <groupId>edu.stanford.swrl</groupId>
            <artifactId>swrlapi-drools-engine</artifactId>
            <version>2.0.4</version>
        </dependency>

        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-osgidistribution</artifactId>
            <version>5.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.25</version>
        </dependency>

Could anyone help me resolve this issue?

**Comment by martinjoconnor** [comment]
The is an example POM for a basic SWRLAPI-based project here:

https://github.com/protegeproject/swrlapi-example/blob/master/pom.xml

You can use the import versions listed there.

**Comment by rayaprolu143** [comment]
Thank you. It worked.
