### ISSUE TITLE
Compilation error creating the SWRL API jar

### ISSUE THREAD

**Issue by cballock** [protegeproject/swrlapi#5]
Hi,
When I tried do generate the SWRLTab project following the instructions found in https://github.com/protegeproject/swrltab-project I got an error when compiling the SWRL API classes:

[ERROR] \Users\carlos.ballock\OneDrive\Documentos\Pessoal\ITA\Disciplinas\CE-261\Software\swrlapi\src\main\java\org\swrlapi\factory\DefaultFileBackedOWLOntologyModel.java:[75,8] error: cannot assign a value to final variable hasOntologyChanged

When I removed the final from the hasOntologyChanged variable the compilation succeded.

The full error stack is the following:

[INFO] Compiling 269 source files to C:\Users\carlos.ballock\OneDrive\Documentos\Pessoal\ITA\Disciplinas\CE-261\Software\swrlapi\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Users\carlos.ballock\OneDrive\Documentos\Pessoal\ITA\Disciplinas\CE-261\Software\swrlapi\src\main\java\org\swrlapi\factory\DefaultFileBackedOWLOntologyModel.java:[70,8] error: cannot assign a value to final variable hasOntologyChanged
[ERROR] \Users\carlos.ballock\OneDrive\Documentos\Pessoal\ITA\Disciplinas\CE-261\Software\swrlapi\src\main\java\org\swrlapi\factory\DefaultFileBackedOWLOntologyModel.java:[75,8] error: cannot assign a value to final variable hasOntologyChanged
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] SWRLAPI ............................................ FAILURE [  9.808 s]
[INFO] Drools SWRLAPI Rule Engine ......................... SKIPPED
[INFO] Standalone SWRLTab ................................. SKIPPED
[INFO] SWRLTab Protege 5.0+ Plugin ........................ SKIPPED
[INFO] SWRLAPI Integration Tests .......................... SKIPPED
[INFO] SWRLTab Project Builder ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.737 s
[INFO] Finished at: 2015-06-19T15:00:35-03:00
[INFO] Final Memory: 23M/319M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swrlapi: Compilation failure: Compilation failure:
[ERROR] \Users\carlos.ballock\OneDrive\Documentos\Pessoal\ITA\Disciplinas\CE-261\Software\swrlapi\src\main\java\org\swrlapi\factory\DefaultFileBackedOWLOntologyModel.java:[70,8] error: cannot assign a value to final variable hasOntologyChanged
[ERROR] \Users\carlos.ballock\OneDrive\Documentos\Pessoal\ITA\Disciplinas\CE-261\Software\swrlapi\src\main\java\org\swrlapi\factory\DefaultFileBackedOWLOntologyModel.java:[75,8] error: cannot assign a value to final variable hasOntologyChanged
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swrlapi: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by martinjoconnor** [comment]
Thanks for the report. Now fixed. Get the latest version of the SWRLAPI project.
